[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "compushady-lrtu"
version = "0.18.0"
description = "GPU Compute module (Vulkan/Linux fork)"
authors = [{ name = "Roberto De Ioris", email = "roberto.deioris@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]